/**
 * Test entry so `node --test lib-test/test/` (a directory argument resolves
 * to `lib-test/test/index.js`) picks up every compiled spec.
 */
import './keep-alive.js'
import './translate.spec.js'
import './chat-completions.spec.js'
import './models.spec.js'
import './catalog-store.spec.js'
import './device-flow.spec.js'
import './copilot.spec.js'
import './tools.spec.js'
import './rpc.spec.js'
import './usage.spec.js'
import './rate-limit.spec.js'
import './detect-cli.spec.js'
import './login.spec.js'
import './store.spec.js'
import './accounts.spec.js'
import './pool.spec.js'
import './pool-health.spec.js'
import './pool-usage.spec.js'
import './grok.spec.js'
import './request-body.spec.js'
import './model-defaults.spec.js'
import './model-defaults-rpc.spec.js'
import './model-defaults-view.spec.js'
import './visibility.test.js'
import './tool-registration.spec.js'
import './token-savings.spec.js'
import './trae.spec.js'
import './cline.spec.js'
// Registered late: this file existed but was never listed here, so its four
// agy thoughtSignature tests silently never ran in the directory run.
import './agy-signature.spec.js'
import './image-request.spec.js'
import './commandcode-catalog-cache.spec.js'
import './commandcode.spec.js'
import './trae-identity.spec.js'
import './trae-refresh.spec.js'
import './trae-region.spec.js'
import './model-vendor.spec.js'
import './cline-auto-configure.spec.js'
import './command.spec.js'
import './modality.spec.js'
