/**
 * The Command Code model table: context window, selectable thinking levels and
 * minimum plan per model id.
 *
 * GENERATED by `scripts/sync-commandcode-models.mjs` from command-code@1.64.0
 * (`dist/bundled/command-code-knowledge/reference/models.md`, itself generated from
 * https://commandcode.ai/docs) — do not hand-edit.

 * ## Why a vendored table at all
 *
 * `GET /provider/v1/models` discloses only
 * `context_length, created, id, name, object, owned_by, supported_endpoints` — it
 * carries NO reasoning metadata, so the thinking-level picker cannot be derived
 * from it. This table is the vendor's own published answer, which is why the plugin
 * DERIVES it here instead of anyone transcribing new models by hand: a hand-kept map
 * is what left `gpt-6-luna` with no selector at all.
 *
 * `efforts: []` is an EXPLICIT "this model has no selectable levels", not an unknown.
 * The distinction is load-bearing: it is what lets a test tell "upstream added a model
 * nobody synced" (absent from this file) from "upstream shipped a model with no level
 * picker" (present with an empty list).
 *
 * The live catalog still wins for CONTEXT: it reports exact token counts and is
 * current the moment a model ships, where this table rounds (`1.05M`).
 *
 * @module dsh-subscription-hub/providers/commandcode-models
 */

/** The CLI release this table was read from. */
export const COMMANDCODE_MODELS_VERSION = "1.64.0"

/** One model as the vendor publishes it. */
export interface CommandCodePublishedModel {
  /** Wire model id, exactly as the catalog spells it. */
  name: string
  /** Display context window, e.g. `1.05M`; the live catalog gives exact tokens. */
  context: string
  /** Selectable thinking levels, in the vendor's order; empty means none. */
  efforts: readonly string[]
  /** Minimum subscription plan, as published. */
  plan: string
}

/** The published table, keyed by model id. */
export const COMMANDCODE_PUBLISHED_MODELS: Readonly<Record<string, CommandCodePublishedModel>> = Object.freeze({
  // DeepSeek V4 Pro (latest) · Go and above · $0.66/$1.98 · cache $0.022
  "deepseek/deepseek-v4-pro": Object.freeze({ name: "DeepSeek V4 Pro (latest)", context: "1M", efforts: Object.freeze(["high","max"]), plan: "Go and above" }),
  // DeepSeek V4 Flash (latest) · Go and above · $0.15/$0.6 · cache $0.003
  "deepseek/deepseek-v4-flash": Object.freeze({ name: "DeepSeek V4 Flash (latest)", context: "1M", efforts: Object.freeze(["high","max"]), plan: "Go and above" }),
  // DeepSeek V4 Flash Vision (exp) · Go and above · $0.15/$0.6 · cache $0.003
  "deepseek/deepseek-v4-flash-vision-exp": Object.freeze({ name: "DeepSeek V4 Flash Vision (exp)", context: "1M", efforts: Object.freeze(["high","max"]), plan: "Go and above" }),
  // DeepSeek V4 Flash Fast · Go and above · $0.28/$0.56 · cache $0.07
  "deepseek/deepseek-v4-flash-fast": Object.freeze({ name: "DeepSeek V4 Flash Fast", context: "1M", efforts: Object.freeze(["low","high","max"]), plan: "Go and above" }),
  // DeepSeek V4.1 Flash · Go and above · $0.15/$0.6 · cache $0.003
  "deepseek/deepseek-v4.1-flash": Object.freeze({ name: "DeepSeek V4.1 Flash", context: "1M", efforts: Object.freeze(["low","high","max"]), plan: "Go and above" }),
  // Kimi K3 · Go and above · $3/$15 · cache $0.3
  "moonshotai/Kimi-K3": Object.freeze({ name: "Kimi K3", context: "1M", efforts: Object.freeze(["low","high","max"]), plan: "Go and above" }),
  // Kimi K2.7 Code · Go and above · $0.95/$4 · cache $0.19
  "moonshotai/Kimi-K2.7-Code": Object.freeze({ name: "Kimi K2.7 Code", context: "256K", efforts: Object.freeze([]), plan: "Go and above" }),
  // Kimi K2.7 Code HighSpeed · Go and above · $1.9/$8 · cache $0.38
  "moonshotai/Kimi-K2.7-Code-Highspeed": Object.freeze({ name: "Kimi K2.7 Code HighSpeed", context: "262K", efforts: Object.freeze([]), plan: "Go and above" }),
  // Kimi K2.6 · Go and above · $0.95/$4 · cache $0.16
  "moonshotai/Kimi-K2.6": Object.freeze({ name: "Kimi K2.6", context: "256K", efforts: Object.freeze([]), plan: "Go and above" }),
  // Kimi K2.5 · Go and above · $0.6/$3 · cache $0.1
  "moonshotai/Kimi-K2.5": Object.freeze({ name: "Kimi K2.5", context: "256K", efforts: Object.freeze([]), plan: "Go and above" }),
  // GLM-5.3 Flash · Go and above · $0.15/$0.5 · cache $0.03
  "z-ai/glm-5.3-flash": Object.freeze({ name: "GLM-5.3 Flash", context: "1.05M", efforts: Object.freeze(["low","high","max"]), plan: "Go and above" }),
  // GLM-5.3 FlashX · Go and above · $0.37/$1.25 · cache $0.075
  "z-ai/glm-5.3-flashx": Object.freeze({ name: "GLM-5.3 FlashX", context: "1M", efforts: Object.freeze(["low","high","max"]), plan: "Go and above" }),
  // GLM-5.3 · Go and above · $1.4/$4.4 · cache $0.26
  "zai-org/GLM-5.3": Object.freeze({ name: "GLM-5.3", context: "1M", efforts: Object.freeze(["low","high","max"]), plan: "Go and above" }),
  // GLM-5.2 · Go and above · $1.4/$4.4 · cache $0.26
  "zai-org/GLM-5.2": Object.freeze({ name: "GLM-5.2", context: "1M", efforts: Object.freeze(["high","max"]), plan: "Go and above" }),
  // GLM-5.2 Fast · Go and above · $3/$10.25 · cache $0.5
  "zai-org/GLM-5.2-Fast": Object.freeze({ name: "GLM-5.2 Fast", context: "1M", efforts: Object.freeze([]), plan: "Go and above" }),
  // GLM-5.1 · Go and above · $1.4/$4.4 · cache $0.26
  "zai-org/GLM-5.1": Object.freeze({ name: "GLM-5.1", context: "", efforts: Object.freeze([]), plan: "Go and above" }),
  // GLM-5 · Go and above · $1/$3.2 · cache $0.2
  "zai-org/GLM-5": Object.freeze({ name: "GLM-5", context: "200K", efforts: Object.freeze([]), plan: "Go and above" }),
  // MiniMax M3 · Go and above · $0.3/$1.2 · cache $0.06
  "MiniMaxAI/MiniMax-M3": Object.freeze({ name: "MiniMax M3", context: "1M", efforts: Object.freeze(["low","medium","high"]), plan: "Go and above" }),
  // MiniMax M2.7 · Go and above · $0.3/$1.2 · cache $0.06
  "MiniMaxAI/MiniMax-M2.7": Object.freeze({ name: "MiniMax M2.7", context: "", efforts: Object.freeze([]), plan: "Go and above" }),
  // MiniMax M2.5 · Go and above · $0.3/$1.2 · cache $0.03
  "MiniMaxAI/MiniMax-M2.5": Object.freeze({ name: "MiniMax M2.5", context: "200K", efforts: Object.freeze([]), plan: "Go and above" }),
  // MiMo V2.6 Pro · Go and above · $0.435/$0.87 · cache $0.0036
  "xiaomi/mimo-v2.6-pro": Object.freeze({ name: "MiMo V2.6 Pro", context: "1.05M", efforts: Object.freeze([]), plan: "Go and above" }),
  // MiMo V2.6 Pro UltraSpeed · GOAT and above · $4.35/$8.7 · cache $0.036
  "xiaomi/mimo-v2.6-pro-ultraspeed": Object.freeze({ name: "MiMo V2.6 Pro UltraSpeed", context: "1.05M", efforts: Object.freeze([]), plan: "GOAT and above" }),
  // MiMo V2.6 Flash · Go and above · $0.14/$0.28 · cache $0.0028
  "xiaomi/mimo-v2.6-flash": Object.freeze({ name: "MiMo V2.6 Flash", context: "1.05M", efforts: Object.freeze([]), plan: "Go and above" }),
  // MiMo V2.5 Pro · Go and above · $0.435/$0.87 · cache $0.0036
  "xiaomi/mimo-v2.5-pro": Object.freeze({ name: "MiMo V2.5 Pro", context: "1M", efforts: Object.freeze([]), plan: "Go and above" }),
  // MiMo V2.5 · Go and above · $0.14/$0.28 · cache $0.0028
  "xiaomi/mimo-v2.5": Object.freeze({ name: "MiMo V2.5", context: "1M", efforts: Object.freeze([]), plan: "Go and above" }),
  // Qwen 3.8 Omni Flash · Go and above · $0.15/$0.47 · cache $0.016
  "Qwen/Qwen3.8-Omni-Flash": Object.freeze({ name: "Qwen 3.8 Omni Flash", context: "1M", efforts: Object.freeze(["low","medium","xhigh"]), plan: "Go and above" }),
  // Qwen 3.8 Max 0902 · Go and above · $2/$6 · cache $0.25
  "Qwen/Qwen3.8-Max-0902": Object.freeze({ name: "Qwen 3.8 Max 0902", context: "1M", efforts: Object.freeze(["low","medium","xhigh"]), plan: "Go and above" }),
  // Qwen 3.8 Max · Go and above · $2/$6 · cache $0.25 (write $2.5)
  "Qwen/Qwen3.8-Max": Object.freeze({ name: "Qwen 3.8 Max", context: "1M", efforts: Object.freeze(["low","medium","xhigh"]), plan: "Go and above" }),
  // Qwen 3.8 27B · Go and above · $0.4/$3 · cache $0.04
  "Qwen/Qwen3.8-27B": Object.freeze({ name: "Qwen 3.8 27B", context: "262K", efforts: Object.freeze(["low","medium","xhigh"]), plan: "Go and above" }),
  // Qwen 3.8 Flash · Go and above · $0.16/$0.47 · cache $0.016
  "Qwen/Qwen3.8-Flash": Object.freeze({ name: "Qwen 3.8 Flash", context: "1M", efforts: Object.freeze(["low","medium","xhigh"]), plan: "Go and above" }),
  // Qwen 3.7 Max · Go and above · $2.5/$7.5 · cache $0.5 (write $3.13)
  "Qwen/Qwen3.7-Max": Object.freeze({ name: "Qwen 3.7 Max", context: "1M", efforts: Object.freeze([]), plan: "Go and above" }),
  // Qwen 3.7 Plus · Go and above · $0.4/$1.6 · cache $0.08 (write $0.5)
  "Qwen/Qwen3.7-Plus": Object.freeze({ name: "Qwen 3.7 Plus", context: "1M", efforts: Object.freeze([]), plan: "Go and above" }),
  // Qwen 3.7 Flash · Go and above · $0.03/$0.13 · cache $0.006 (write $0.038)
  "Qwen/Qwen3.7-Flash": Object.freeze({ name: "Qwen 3.7 Flash", context: "1M", efforts: Object.freeze([]), plan: "Go and above" }),
  // Qwen 3.6 Max Preview · Go and above · $1.3/$7.8 · cache $0.26 (write $1.63)
  "Qwen/Qwen3.6-Max-Preview": Object.freeze({ name: "Qwen 3.6 Max Preview", context: "", efforts: Object.freeze([]), plan: "Go and above" }),
  // Qwen 3.6 Plus · Go and above · $0.5/$3 · cache $0.1
  "Qwen/Qwen3.6-Plus": Object.freeze({ name: "Qwen 3.6 Plus", context: "", efforts: Object.freeze([]), plan: "Go and above" }),
  // LongCat 2.0 · Go and above · $0.3/$1.2 · cache $0.006
  "meituan/LongCat-2.0": Object.freeze({ name: "LongCat 2.0", context: "1.05M", efforts: Object.freeze([]), plan: "Go and above" }),
  // Step 5 Preview · Go and above · $1/$2.7 · cache $0.05
  "stepfun/Step-5-Preview": Object.freeze({ name: "Step 5 Preview", context: "1M", efforts: Object.freeze(["low","medium","high"]), plan: "Go and above" }),
  // Step 3.7 Flash · Go and above · $0.2/$1.15 · cache $0.04
  "stepfun/Step-3.7-Flash": Object.freeze({ name: "Step 3.7 Flash", context: "256K", efforts: Object.freeze([]), plan: "Go and above" }),
  // Step 3.5 Flash · Go and above · $0.1/$0.3 · cache $0.02
  "stepfun/Step-3.5-Flash": Object.freeze({ name: "Step 3.5 Flash", context: "1M", efforts: Object.freeze([]), plan: "Go and above" }),
  // Tencent Hy3 · Go and above · $0.14/$0.58 · cache $0.035
  "tencent/hy3-paid": Object.freeze({ name: "Tencent Hy3", context: "262K", efforts: Object.freeze([]), plan: "Go and above" }),
  // Tencent Hy4 Preview · Go and above · $0.834/$2.501 · cache $0.042
  "tencent/hy4-preview": Object.freeze({ name: "Tencent Hy4 Preview", context: "1.05M", efforts: Object.freeze(["low","medium","high"]), plan: "Go and above" }),
  // Nemotron 3 Ultra · Go and above · $0.6/$2.4 · cache $0.12
  "nvidia/nemotron-3-ultra-550b-a55b": Object.freeze({ name: "Nemotron 3 Ultra", context: "1M", efforts: Object.freeze([]), plan: "Go and above" }),
  // Inkling · Go and above · $1/$4.05 · cache $0.17
  "thinkingmachines/inkling": Object.freeze({ name: "Inkling", context: "256K", efforts: Object.freeze([]), plan: "Go and above" }),
  // Inkling Small · Go and above · $0.5/$1.2 · cache $0.1
  "thinkingmachines/inkling-small": Object.freeze({ name: "Inkling Small", context: "1M", efforts: Object.freeze([]), plan: "Go and above" }),
  // Laguna S 2.1 · Go and above · $0/$0 · cache $0
  "poolside/laguna-s-2.1-free": Object.freeze({ name: "Laguna S 2.1", context: "256K", efforts: Object.freeze([]), plan: "Go and above" }),
  // Ling 3.0 Flash Sante · Go and above · $0/$0 · cache $0
  "inclusionai/ling-3.0-flash-sante:free": Object.freeze({ name: "Ling 3.0 Flash Sante", context: "262K", efforts: Object.freeze([]), plan: "Go and above" }),
  // Claude Sonnet 5 · Pro and above · $2/$10 · cache $0.2 (write $2.5)
  "claude-sonnet-5": Object.freeze({ name: "Claude Sonnet 5", context: "1M", efforts: Object.freeze(["low","medium","high","xhigh","max"]), plan: "Pro and above" }),
  // Claude Sonnet 4.6 · Pro and above · $3/$15 · cache $0.3 (write $3.75)
  "claude-sonnet-4-6": Object.freeze({ name: "Claude Sonnet 4.6", context: "1M", efforts: Object.freeze(["low","medium","high","xhigh","max"]), plan: "Pro and above" }),
  // Claude Fable 5.1 · Max · $10/$50 · cache $0.25 (write $12.5)
  "claude-fable-5-1": Object.freeze({ name: "Claude Fable 5.1", context: "1M", efforts: Object.freeze(["low","medium","high","xhigh","max"]), plan: "Max" }),
  // Claude Fable 5 · Max · $10/$50 · cache $1 (write $12.5)
  "claude-fable-5": Object.freeze({ name: "Claude Fable 5", context: "1M", efforts: Object.freeze(["low","medium","high","xhigh","max"]), plan: "Max" }),
  // Claude Opus 5.5 · Max · $4/$20 · cache $0.2 (write $5)
  "claude-opus-5-5": Object.freeze({ name: "Claude Opus 5.5", context: "1M", efforts: Object.freeze(["low","medium","high","xhigh","max"]), plan: "Max" }),
  // Claude Opus 5 · Max · $5/$25 · cache $0.5 (write $6.25)
  "claude-opus-5": Object.freeze({ name: "Claude Opus 5", context: "1M", efforts: Object.freeze(["low","medium","high","xhigh","max"]), plan: "Max" }),
  // Claude Opus 4.8 · Max · $5/$25 · cache $0.5 (write $6.25)
  "claude-opus-4-8": Object.freeze({ name: "Claude Opus 4.8", context: "1M", efforts: Object.freeze(["low","medium","high","xhigh","max"]), plan: "Max" }),
  // Claude Opus 4.7 · Max · $5/$25 · cache $0.5 (write $6.25)
  "claude-opus-4-7": Object.freeze({ name: "Claude Opus 4.7", context: "1M", efforts: Object.freeze(["low","medium","high","xhigh","max"]), plan: "Max" }),
  // Claude Haiku 4.5 · Pro and above · $1/$5 · cache $0.1 (write $1.25)
  "claude-haiku-4-5-20251001": Object.freeze({ name: "Claude Haiku 4.5", context: "200K", efforts: Object.freeze([]), plan: "Pro and above" }),
  // GPT-6 Astra · Max · $10/$50 · cache $1 (write $12.5)
  "gpt-6-astra": Object.freeze({ name: "GPT-6 Astra", context: "1.05M", efforts: Object.freeze(["low","medium","high","xhigh","max"]), plan: "Max" }),
  // GPT-6 Sol · Pro and above · $2/$10 · cache $0.2 (write $2.5)
  "gpt-6-sol": Object.freeze({ name: "GPT-6 Sol", context: "1.05M", efforts: Object.freeze(["low","medium","high","xhigh","max"]), plan: "Pro and above" }),
  // GPT-6 Luna · Go and above · $0.1/$0.5 · cache $0.01 (write $0.125)
  "gpt-6-luna": Object.freeze({ name: "GPT-6 Luna", context: "1.05M", efforts: Object.freeze(["low","medium","high","xhigh","max"]), plan: "Go and above" }),
  // GPT-5.6 Sol · GOAT and above · $5/$30 · cache $0.5 (write $6.25)
  "gpt-5.6-sol": Object.freeze({ name: "GPT-5.6 Sol", context: "1.05M", efforts: Object.freeze(["low","medium","high","xhigh","max"]), plan: "GOAT and above" }),
  // GPT-5.6 Terra · Pro and above · $2/$12 · cache $0.2 (write $2.5)
  "gpt-5.6-terra": Object.freeze({ name: "GPT-5.6 Terra", context: "1.05M", efforts: Object.freeze(["low","medium","high","xhigh","max"]), plan: "Pro and above" }),
  // GPT-5.6 Luna · Go and above · $0.2/$1.2 · cache $0.02 (write $0.25)
  "gpt-5.6-luna": Object.freeze({ name: "GPT-5.6 Luna", context: "1.05M", efforts: Object.freeze(["low","medium","high","xhigh","max"]), plan: "Go and above" }),
  // GPT-5.5 · Pro and above · $5/$30 · cache $0.5 (write $0)
  "gpt-5.5": Object.freeze({ name: "GPT-5.5", context: "400K", efforts: Object.freeze(["low","medium","high","xhigh"]), plan: "Pro and above" }),
  // GPT-5.4 · Pro and above · $2.5/$15 · cache $0.25 (write $0)
  "gpt-5.4": Object.freeze({ name: "GPT-5.4", context: "400K", efforts: Object.freeze(["low","medium","high","xhigh"]), plan: "Pro and above" }),
  // GPT-5.3 Codex · Pro and above · $2/$8 · cache $0.5 (write $0)
  "gpt-5.3-codex": Object.freeze({ name: "GPT-5.3 Codex", context: "400K", efforts: Object.freeze(["low","medium","high","xhigh"]), plan: "Pro and above" }),
  // GPT-5.4 Mini · Pro and above · $0.75/$4.5 · cache $0.075 (write $0)
  "gpt-5.4-mini": Object.freeze({ name: "GPT-5.4 Mini", context: "400K", efforts: Object.freeze(["low","medium","high"]), plan: "Pro and above" }),
  // Gemini 3.8 Flash · GOAT and above · $1.5/$7.5 · cache $0.15
  "google/gemini-3.8-flash": Object.freeze({ name: "Gemini 3.8 Flash", context: "1M", efforts: Object.freeze(["low","medium","high"]), plan: "GOAT and above" }),
  // Gemini 3.7 Flash · GOAT and above · $1.5/$7.5 · cache $0.15 (write $0.08334)
  "google/gemini-3.7-flash": Object.freeze({ name: "Gemini 3.7 Flash", context: "1.05M", efforts: Object.freeze(["low","medium","high"]), plan: "GOAT and above" }),
  // Gemini 3.6 Flash · Pro and above · $1.5/$7.5 · cache $0.15
  "google/gemini-3.6-flash": Object.freeze({ name: "Gemini 3.6 Flash", context: "1M", efforts: Object.freeze(["low","medium","high"]), plan: "Pro and above" }),
  // Gemini 3.5 Flash · Pro and above · $1.5/$9 · cache $0.15
  "google/gemini-3.5-flash": Object.freeze({ name: "Gemini 3.5 Flash", context: "1M", efforts: Object.freeze(["low","medium","high"]), plan: "Pro and above" }),
  // Gemini 3.5 Flash Lite · Pro and above · $0.3/$2.5 · cache $0.03
  "google/gemini-3.5-flash-lite": Object.freeze({ name: "Gemini 3.5 Flash Lite", context: "1M", efforts: Object.freeze(["low","medium","high"]), plan: "Pro and above" }),
  // Gemini 3.1 Flash Lite · Pro and above · $0.25/$1.5 · cache $0.03
  "google/gemini-3.1-flash-lite": Object.freeze({ name: "Gemini 3.1 Flash Lite", context: "1M", efforts: Object.freeze(["low","medium","high"]), plan: "Pro and above" }),
  // Fugu Ultra · Max · $5/$30 · cache $0.5
  "sakana/fugu-ultra": Object.freeze({ name: "Fugu Ultra", context: "1M", efforts: Object.freeze(["high","xhigh"]), plan: "Max" }),
  // Muse Spark 1.1 · Pro and above · $1.25/$4.25 · cache $0.15
  "meta/muse-spark-1.1": Object.freeze({ name: "Muse Spark 1.1", context: "1.05M", efforts: Object.freeze(["low","medium","high","xhigh"]), plan: "Pro and above" }),
  // Muse Spark 1.2 · GOAT and above · $1.25/$4.25 · cache $0.15
  "meta/muse-spark-1.2": Object.freeze({ name: "Muse Spark 1.2", context: "1.05M", efforts: Object.freeze(["low","medium","high","xhigh"]), plan: "GOAT and above" }),
  // Muse Spark 1.2 Contributor · Go and above · $0.1/$0.2 · cache $0.002
  "meta/muse-spark-1.2-contributor": Object.freeze({ name: "Muse Spark 1.2 Contributor", context: "1.05M", efforts: Object.freeze(["low","medium","high","xhigh"]), plan: "Go and above" }),
  // Muse Spark 1.3 · GOAT and above · $1.25/$4.25 · cache $0.15
  "meta/muse-spark-1.3": Object.freeze({ name: "Muse Spark 1.3", context: "1.05M", efforts: Object.freeze(["low","medium","high","xhigh","max"]), plan: "GOAT and above" }),
  // Muse Spark 1.3 Contributor · Go and above · $0.1/$0.2 · cache $0.002
  "meta/muse-spark-1.3-contributor": Object.freeze({ name: "Muse Spark 1.3 Contributor", context: "1.05M", efforts: Object.freeze(["low","medium","high","xhigh"]), plan: "Go and above" }),
  // Grok 4.5 · Go and above · $2/$6 · cache $0.5
  "xai/grok-4.5": Object.freeze({ name: "Grok 4.5", context: "500K", efforts: Object.freeze(["low","medium","high"]), plan: "Go and above" }),
  // Grok 4.6 · GOAT and above · $2/$6 · cache $0.5
  "xai/grok-4.6": Object.freeze({ name: "Grok 4.6", context: "500K", efforts: Object.freeze(["low","medium","high","xhigh"]), plan: "GOAT and above" }),
  // Grok 4.7 · GOAT and above · $1.2/$3.6 · cache $0.3
  "xai/grok-4.7": Object.freeze({ name: "Grok 4.7", context: "500K", efforts: Object.freeze(["low","medium","high","xhigh"]), plan: "GOAT and above" }),
})

